// Provider type definitions
export type SystemProviderId =
  | 'openai'
  | 'openai-responses'
  | 'anthropic'
  | 'google'
  | 'azure'
  | 'openai-compatible'
  | 'openrouter'
  | 'xai'
  | 'deepseek'
  | 'ollama'
  | 'burncloud'
  | 'togetherai'
  | 'groq'
  | 'cohere'
  | 'mistral'

export type ProviderTypeId =
  | 'openai'
  | 'openai-response'
  | 'anthropic'
  | 'google'
  | 'azure'
  | 'openai-compatible'
  | 'openrouter'
  | 'xai'
  | 'deepseek'
  | 'ollama'
  | 'togetherai'
  | 'groq'
  | 'cohere'
  | 'mistral'
