name: Build Android
run-name: Creating Production Ready Android App 🚀
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build APK
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Setup .env
        run: cp .env.app .env.local

      - name: Build frontend
        run: pnpm build

      - name: Determine tag
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          fi

      - name: Ensure release exists
        id: ensure_release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG='${{ steps.vars.outputs.tag }}'
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "release_id=${{ github.event.release.id }}" >> "$GITHUB_OUTPUT"
          else
            if ! gh release view "$TAG" >/dev/null 2>&1; then
              gh release create "$TAG" -t "$TAG" -n "Automated release" || exit 1
            fi
            echo "release_id=$(gh release view "$TAG" --json id -q .id)" >> "$GITHUB_OUTPUT"
          fi

      - name: Add android folder if not present
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Capacitor sync
        run: npx cap sync

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > android/release.decrypted.jks

      - name: Set gradlew permissions
        run: chmod +x ./android/gradlew

      - name: Build Release APK
        working-directory: ./android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/android/release.decrypted.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

      - name: Zip spa bundle
        working-directory: ./dist/spa
        run: zip -qq -r ../../spa.zip .

      - name: Upload assets to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG='${{ steps.vars.outputs.tag }}'
          gh release upload "$TAG" \
            "./android/app/build/outputs/apk/release/app-release.apk#AIaW_${TAG}.apk" \
            "./spa.zip#spa_bundle_${TAG}.zip" \
            "./src/version.json" \
            --clobber
