name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name (e.g. v1.8.4)
        required: true
      title:
        description: Release title (defaults to tag)
        required: false
      notes:
        description: Release notes (leave empty to auto-generate)
        required: false

jobs:
  create:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.title || inputs.tag }}
          body: ${{ inputs.notes }}
          generate_release_notes: ${{ inputs.notes == '' }}
